version: "3"

services:
  nginx:
    image: nginx:latest
    ports:
      - 6666:80
    volumes:
      - ./www/html/:/var/www/html/
      - ./nginx/:/etc/nginx/conf.d
    networks:
      - backend
      - frontend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
    depends_on:
      - php
  php:
    image: php:7.0-fpm
    volumes:
      - ./www/html/:/var/www/html/
    networks:
      - backend
    deploy:
      replicas: 1
      update_config:
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure
  mysql:
    image: mysql:latest
    # ustawienie zmiennych środowiskowych
    environment:
      # zmienne w ${} wskazują na plik .env
        MYSQL_ROOT_PASSWORD: root
        # nazwa usera
        MYSQL_USER: test
        # haslo usera
        MYSQL_PASSWORD: test
    # podłączenie do sieci backend
    networks:
      - backend
    deploy:
      placement:
        constraints: [node.role == manager]
  # serwis phpmyadmin
  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    # ustawienie zmiennych środowiskowych
    environment:
      PMA_HOST: mysql
      MYSQL_ROOT_PASSWORD: root
      # ustawienie portu
    ports:
      - 6001:80
    # ustawienie sieci backend
    networks:
      - backend
    deploy:
      replicas: 1
      update_config: 
        parallelism: 2
        delay: 10s
      restart_policy:
        condition: on-failure

# utworzone sieci
networks:
  frontend:
  backend: